on:
  pull_request:
    branches:
      - deploy
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
        
      - name: Download Dependencies
        run: go mod download
        
      - name: Build
        run: CGO_ENABLED=0 go build -tags=release -o ./build/go_build_linux_linux ./main.go
        
      - name: Deploy to Aliyun
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./build/"
          TARGET: ${{ secrets.REMOTE_TARGET }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SCRIPT_BEFORE: |
            supervisorctl stop animelife
          SCRIPT_AFTER: |
            supervisorctl start animelife
      
