on:
  pull_request:
    branches:
    - deploy
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
        
      - name: Download Dependencies
        run: go mod download
        
      - name: Set current date
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
        
      - name: Build
        run: go build -tags=release -o ./build/go_build_linux_linux_$CURRENT_DATE ./main.go
        env:
          CURRENT_DATE: ${{ steps.date.outputs.date }}
        
      - name: Deploy to Aliyun
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./build/"
          TARGET: ${{ secrets.REMOTE_TARGET }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
      
