on:
  pull_request:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: SetUpGoEnv
      uses: actions/setup-go@master
      with:
        go-version: 1.20
        
    - name: Build
      run: go build -tags=release -o ./go_build_linux_linux ./main.go
      
    - name: Deploy to Aliyun
      uses: easingthemes/ssh-deploy@v4.1.8
      with:
        SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./"
        TARGET: "/root/AnimeLife/BackendCI"
        REMOTE_HOST:  ${{ secrets.ALIYUN_SERVER_HOST }}
        REMOTE_USER: "root"
