on:
  workflow_dispatch:
  
jobs:
  set_up_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
        
      - name: ls
        run: ls . -l
        
      - name: Go get
        run: go mod download
        
      - name: Build
        run: go build -tags=release -o ./go_build_linux_linux ./main.go
      
